### PR TITLE
Feature - BrickLinkApiError - throwing an error object with error details

### PR DESCRIPTION
**Pull request by ofir-shapira-como**
Docs were auto-generate, added `.idea` folder to `.gitignore`

Added a test to `spec/client.spec.js`
Created a new object `src/brickLinkApiError.js`
Edited the client to throw that error object `src/client.js`

### CODE REVIEW

**Comment by ryansh100** [comment]
I'm not seeing where `BricklinkResponseMeta` class is used, I would prefer to just remove.

https://github.com/ryansh100/bricklink-api/pull/36/files#diff-5a2fe78d77eb63824f92439dc8c8d8a7b658d1891f514bbe722733f288e7d6b4R17

**Comment by ofir-shapira-como** [comment]
Can remove it, wanted it for easier auto-completion and to have type annotation

image

Your call, should I remove?

**Comment by ofir-shapira-como** [comment]
Makes more sense to remove it, I'll do it

**Comment by ryansh100** [comment]
I see, to put the definition in use, we would use in jsdoc here:

image

I don't believe that I have done my comment totally correct  there, to be honest.

**Comment by ofir-shapira-como** [comment]
Nice one, so I used jsdoc nested object:

```js
export class BrickLinkApiError extends Error {
    /**
     * Create a BrickLink error exception object.
     * @param {Object} meta The object containing error data.
     * @param {number} meta.code The HTTP response status code.
     * @param {string} meta.message The error message.
     * @param {string} meta.description The error description.
     */
    constructor(meta) {
        super(meta.message);
        this.name = this.constructor.name;
        this.meta = meta;
    }
}
```

with this in the test spec:

```js
test('Will throw BrickLinkApiError exception if the Bricklink servers return an error code', (t) => {
    const request = Color.get(400000000000000000);
    return t.throwsAsync(() => BL.send(request), {
        instanceOf: BrickLinkApiError,
        message: 'PARAMETER_MISSING_OR_INVALID'
    }).then(
        /**
         * @param {BrickLinkApiError} error The object containing error data.
         */
        error => {
            t.is(error.meta.code, 400);
            t.is(error.meta.description, 'Unparseable data [400000000000000000] for [color_id].');
            t.is(error.meta.message, 'PARAMETER_MISSING_OR_INVALID');
        });
});
```

**Review by ryansh100 — APPROVED** [review]
Not sure why github actions has recently broken the secrets, but I don't believe that there are any major concerns here.

**Pull request merged**
